# Generated by Django 5.1.3 on 2025-04-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_about_login_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
