# Generated by Django 5.1.3 on 2025-04-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_name_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='email',
        ),
    ]
